FILES=memalloc.h my_memory.c

compile_1: $(FILES)
	gcc test1.c $(FILES) -g -o memory_test_1

compile_2: $(FILES)
	gcc test2.c $(FILES) -g -o memory_test_2

compile_3: $(FILES)
	gcc test3.c $(FILES) -g -o memory_test_3

compile_4: $(FILES)
	gcc test4.c $(FILES) -g -o memory_test_4

compile_5: $(FILES)
	gcc test5.c $(FILES) -g -o memory_test_5

compile_6: $(FILES)
	gcc test6.c $(FILES) -g -o memory_test_6

compile_7: $(FILES)
	gcc test7.c $(FILES) -g -o memory_test_7

compile_8: $(FILES)
	gcc test8.c $(FILES) -g -o memory_test_8