FILES=test1.c memalloc.h my_memory.c

compile_1: $(FILES)
	gcc $(FILES) -g -o memory_test_1

compile_2: $(FILES)
	gcc $(FILES) -g -o memory_test_2

compile_3: $(FILES)
	gcc $(FILES) -g -o memory_test_3

compile_4: $(FILES)
	gcc $(FILES) -g -o memory_test_4

compile_5: $(FILES)
	gcc $(FILES) -g -o memory_test_5

compile_6: $(FILES)
	gcc $(FILES) -g -o memory_test_6

compile_7: $(FILES)
	gcc $(FILES) -g -o memory_test_7

compile_8: $(FILES)
	gcc $(FILES) -g -o memory_test_8